### ISSUE TITLE
KF 1.7: Rebase onto 1.7 centraldashboard

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/kubeflow#135]
EPIC: https://github.com/StatCan/daaas/issues/1632

Old rebase for 1.6: https://github.com/StatCan/kubeflow/pull/99

After discussing with Bryan we agreed that this would be a difficult issue to split out, so we will just have one big ticket likely worked on by just one developer for a sprint. 

I think we will be able to take mostly upstream, and then anything in central-dashboard we will need to determine our customizations, probably Mathis is the best bet for getting that done well and in a good amount of time as he has worked the most on frontend.

```
git remote add upstream https://github.com/kubeflow/kubeflow/
git fetch upstream # This allows us to have all upstream branches available
git checkout upstream/master # make sure you have the forked repo's master locally
git checkout stc-master
git pull
git checkout -b {your-new-branch-to-rebase-fork}
git reset $(git merge-base upstream/master $(git branch --show-current)) # this will reset your current branch to a good merge base between it and the upstream master, essentially the idea is to undo all commits not on upstream master
git add .
git commit -m "commit message"
git rebase upstream/v1.7.0
```

Another possible way.
```
git clone https://github.com/StatCan/kubeflow
cd kubeflow
git remote add upstream https://github.com/kubeflow/kubeflow
git fetch upstream
git remote –v # check remotes are configured correctly
git checkout stc-master
git checkout –b bryan-rebase-1.4-to-1.6
git rebase v1.6.0
# resolve conflicts...
git commit -m "rebase message..."
git push --set-upstream origin bryan-rebase-1.4-to-1.6
```

The important folders

```
components/centraldashboard
components/notebook-controller
.github/workflows
```

**Comment by wg102** [comment]
There are a total of 230 conflicting files. I will not be making a list of them since VSCode has a reliable feature to deal with them.

Something to test in the future is in the settings of vscode there is a merge setting to have code side by side in conflicting files instread of with the `<<<< HEAD` code changes. Unfortunately, some of the code seems to have no conflict in that setting, so I will still do it by hand to insure the compliance.

**Comment by wg102** [comment]
Notes while doing the code:
- [ ] components/admission-webhook/manifest/base/crd.yaml : Manifest file has changed a lot. Since our manifest is not in the same repo as our code, we might have to update them as well. Unknown difficulty yet.

- [ ] kubeflow/components/admission-webhook/manifests/base/kustomization.yaml :    newName: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook seems to be our image. will need to update
- [ ] components/centraldashboard/manifests/base/configmap.yaml Renamed model text to Endpoints
- [ ] kubeflow/components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml Same 
- [ ] Will need to check if deprecated-jupyter is in the changes when trying to pull request
- [ ] FROM node:12.22.12-bullseye AS build  --- FROM node:16-alpine AS build
- [ ] i18n components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/positive-number-input/positive-number-input.component.html linting added spaces to the i18n text. Might need to be updated
- [ ] Almost all test got WaitForAsync function added into them
- [ ] components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/namespace-select/namespace-select.component.html New function to select All namespaces
- [ ] components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html the [attr.data-cy-resource-table-row]="col.matColumnDef" is new for all tables
- [ ] components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/property-value.ts Removed everything related to isLink
- [ ] example-notebook-servers has a new key work REgistry. It might change how it works
- [ ] components/example-notebook-servers/rstudio/Dockerfile Rstudio version changed
- [ ] components/notebook-controller/controllers/notebook_controller.go Update on how the podFound works. 
- [ ] components/centraldashboard/Dockerfile Kept alpine-16 instead of downgrading to 12.  modified the line with gnui, we don't have git like we use to

**Comment by wg102** [comment]
Work done in the following branch: https://github.com/StatCan/kubeflow/tree/kf1.7-upgrade

Since the rest of the work will be done in the same, there will not be a code review for this one.
