### ISSUE TITLE
Profile owner can only manage one profile in UI

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#7]
When a user owns more than one KF Profile and tries to manage contributors, only one profile is displayed for management – seems to be lexicographically first that's displayed.

Instead, a user should be able to manage contributors for all Profiles they own.

Upstream: kubeflow/kubeflow/issues/4569

**Comment by blairdrummond** [comment]
There's been some activity in the upstream issue

https://github.com/kubeflow/kubeflow/issues/4569#issuecomment-669902459

Looks like they have a manual way now? CC @brendangadd @justbert @sylus

**Comment by frazs** [comment]
Work on this issue was delayed on my end in part because my usual dev environment lacks the resources for a local instance of Kubeflow, while installation attempts on my Azure VMs failed. I made a separate issue for setting up a virtual local Kubeflow dev environment: https://github.com/StatCan/kubeflow/issues/15. 

For now, I do have another machine at home that seems to have installed minikf successfully. It is not optimal for work, but it will be much faster for me to try to work on this issue there now in the short-term, than to context switch into a long-term solution for the otherwise separate https://github.com/StatCan/kubeflow/issues/15.

**Comment by frazs** [comment]
So far the only way I've found access to the components I need to modify is by building the central dashboard as a docker image inside the vagrant box of minikf and then using the resulting image to replace the centraldashboard image. Otherwise, the necessary components do not load. Even with this solution, some components do not load (`'configmaps "centraldashboard-links-config" is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot get resource "configmaps" in API group "" in the namespace "kubeflow"'`; `events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "bob-ross-pics-rise-again"'`), but they are not relevant to this issue. 

The build process is time consuming. It is also cancelled by the BDD framework Jasmine, which I am not familiar with. For now, to be able to proceed at all, I have temporarily deleted the test file for the manage contributors page. I can figure that out later.

The issue itself is non-trivial as the "owned namespace" is defined as, and expected to be, a single object whereas namespaces are otherwise an array. This is across pug, polymer, and some form of ECMAScript, none of which I am familiar with. So far my experiments have only led to components vanishing, and I've yet to discover any corresponding error messages.

**Comment by frazs** [comment]
Brendan found a way to connect with `npm run dev`, which skips the time consuming docker build / image replacement steps, and also bypasses the test check:
1. Replace https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/webpack.config.js#L197 with https://github.com/StatCan/kubeflow/blob/stc-master/components/centraldashboard/webpack.config.js#L200-L206
2. `kubectl port-forward -n kubeflow deployment/profiles-deployment 8081:8081`
3. For connection to the production cluster, `USERID_HEADER=kubeflow-userid USERID_PREFIX= KF_USER_ID=[name@cloud.statcan.ca, e.g. frances.zsurka@cloud.statcan.ca] npm run dev`

This can fail with ambiguous errors on the latest node version, however the latest LTS v12.8.3 works. I use [nvm](https://github.com/nvm-sh/nvm) to make sure I'm on the right one.

This is sufficient to load profiles and the "Manage Contributors" interface, which is all I need for this issue, but does not successfully load other assets.

There is most likely a way for this to work with minikf, but I'd need to determine what headers it expects. I will be cautiously working connected to prod unless minikf becomes necessary, given that this issue should be doable without changes to the cluster beyond the creation of a dummy profile or two. The only machine I have capable of running minikf is not physically set up for a proper working environment, and while I could set up a remote connection, that would take some additional time to figure out how to set up effectively + securely (though if someone has a good reference do pass it along!).

**Comment by blairdrummond** [comment]
Is this still being worked on?

**Comment by frazs** [comment]
I am switching teams next week and presently still finalizing some high-priority knowledge transfer. I hope to still find some remaining time to continue working on this issue. I will have an update Friday night: if I cannot wrap this up, I will deliver a WIP draft pull request and some documentation (e.g. how to connect/test, what worked, what didn't work, how I intended to continue, pitfalls to be aware of) so that somebody else would be able to pick up where I left off.
