### ISSUE TITLE
Move assets (e.g. fonts) into the service

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#9]
Move assets into the service so issues with external services don't affect ours. We've experienced some issues with page load being blocked, waiting on `fonts.gstatic.com`.

**Comment by saffaalvi** [comment]
Created a new branch: https://github.com/StatCan/kubeflow/tree/9-add-fonts-to-assets where I created a new folder in `components/centraldashboard/public/assets` containing all the `.woff2` files for the fonts used.
Then, referenced those instead of the remote ones in `components/centraldashboard/public/styles.css`.
Haven't created a PR since I can't fully test this yet.
